= 3205 Assistance Units
:chapter-number: 3200
:effective-date: June 2026
:mt: MT-87
:policy-number: 3205
:policy-title: Assistance Units
:previous-mt-number: MT-81

include::partial$policy-header.adoc[]

== Codes and References

7 CFR § 273.1

== Requirements

A Supplemental Nutrition Assistance Program (SNAP) Assistance Unit (AU) includes eligible individual(s) who live together and customarily purchase food and prepare meals in common.

== Basic Considerations

The following criteria are considered in determining a SNAP AU:

* the individuals living at the residence
* the individuals who purchase food and prepare meals together
* the individuals who intend to purchase food and prepare meals together upon receipt of the SNAP benefits
* the type of residence (e.g., house, room, shelter, institution)
* the age and disability of the individuals
* the relationship of the individuals.

Individuals who live together but who purchase food and prepare meals separately may be eligible to receive benefits as separate AUs, with the following considerations:

* each AU must declare a separate AU status
* the AU members are not required to store food separately from those with whom they reside to be considered a separate AU.
* separate AU status is not verified unless questionable.

Refer to Procedures in this section for a list of individuals to be included and excluded for AU composition.

The AU is not required to have cooking facilities available as a condition of SNAP eligibility.

== Procedures

Follow the steps below to determine the composition of a SNAP AU.

[horizontal,labelwidth=10]
Step 1:: Include the individuals who purchase food and prepare meals together.

Step 2:: Consider a potential separate AU status if one or more household members state that they are a separate AU or intend to purchase food and prepare meals separately.

Step 3:: Include the following individuals in one AU, even if they state they purchase and prepare meals as a separate AU:

* Spouses (including common-law marriages which started prior to 7/1/97)
Under Georgia Law, effective 7/1/97, common-law marriages are not recognized, unless the marriage started prior to that date

* Minor children under 18 who are under the parental control of an AU member other than their parent

* Parents and their children under the age of 22 (biological, adopted, or step), even if the child is living with his/her spouse and/or his/her own children

Step 4:: Exclude the following individuals from the AU, even if they customarily purchase food and prepare meals together:

* an individual who is IPV disqualified
* an individual who is enumeration sanctioned
* an individual who is work sanctioned
* an ineligible student
* an ineligible ABAWD
* an individual who is a fleeing felon or probation/parole violator
* an individual who committed and was convicted by federal, state, or local court, after 8/22/96, of an offense classified as a felony related to possession, use, or distribution of a controlled substance (lawbreaker) and violates the terms of their probation as determined by a court order or violates the terms of their parole as determined by a State Board of Pardons and Paroles order
* an individual convicted as an adult of aggravated sexual abuse, murder, sexual exploitation, and other abuse of children, a Federal or State offense involving sexual assault, or an offense under State law determined by the Attorney General to be substantially similar to such an offense, after 2/7/14 and violates the terms of their probation as determined by a court order or violates the terms of their parole as determined by a State Board of Pardons and Paroles order

Refer to <<chart-3205-1,Chart 3205.1, Determining the Composition of a SNAP AU>>.

NOTE: Refer to xref:3600.adoc[] for how to budget excluded AU members' resources and income.

== Verification

Accept the A/R's statement to determine the AU composition, unless the information provided is questionable and/or conflicts with other information available to the agency.

If third-party verification is required, obtain current verification from one of the following sources:

* a statement from a landlord
* a statement from a person outside of the AU who has knowledge of the AU's situation
* school records (for school-age children)
* any other source that verifies the A/R's statement.

NOTE: This is not an all-inclusive list.

Use the following chart to determine the composition of the SNAP AU in special situations.

[#chart-3205-1]
.Chart 3205.1 - Determining the Composition of a SNAP AU
|===
^| SPECIAL AU MEMBERS ^| TREATMENT

| Aliens
| Include aliens who meet the eligible alien requirements.
Exclude those who are considered ineligible aliens because of failure to meet the criteria of a SNAP-eligible alien group.
Refer to xref:3320.adoc[] and xref:3635.adoc[].

| Boarder
| An individual or groups of individuals residing with others and paying reasonable compensation for lodging and meals.
A boarder can never participate as a separate AU.

|Boarder Not in a Commercial Boarding House
a| To determine if an individual living with an AU meets the definition of a boarder or if s/he must be included as an AU member, determine if reasonable compensation is paid by using the following criteria.

* The individual or family receiving *more than two meals daily* from the boarding household must pay an amount equal to or exceeding the maximum monthly SNAP allotment for the appropriate number of individuals.

* The individual or family receiving *one or two meals daily* from the boarding household must pay an amount equal to or exceeding two-thirds of the maximum monthly SNAP allotment for the appropriate number of individuals.

NOTE: If less than reasonable compensation as defined above is paid, the individual or family cannot be considered a boarder(s) and must be included as a member(s) of the AU.

Refer to xref:3425.adoc[] for instructions on how to budget boarder payments
| Boarder in a Commercial Boarding House
| Exclude the boarder from any SNAP AU.
A boarder in a commercial boarding house is ineligible to participate.
Refer to the Glossary for the definition of a commercial boarding house.

| An individual considered permanently disabled under the Social Security Act (refer to the definition of  disabled in the Glossary) or suffers from a non-disease related, severe, permanent disability and who is 60 years or older, living and eating with others because of the inability to purchase and prepare his/her own meals
a| Determine eligibility for the disabled person and spouse as a separate AU if the gross income of the others with whom the individual resides does not exceed 165% of the Federal Poverty Level (FPL).
The table showing 165% of the FPL is located in xref:appendix-a-financial-standards-overview.adoc[].

NOTE: The age and health of the spouse are not considerations.

| Foster Care Children or Adults or Children Placed through Relative Care Subsidy.
a| Allow the foster or relative care family the option to include as a member(s) of their AU the foster child(ren), foster adult(s) or relative care children placed in the home by DFCS.

If the AU chooses to include the foster or relative care individual(s), include the foster care per diem or relative care subsidy and all other income and resources of the foster or relative care individual.

If the AU chooses to exclude the foster or relative care individual(s), *DO NOT* count the foster care per diem or relative care subsidy or any other income/resources of the foster or relative care individual.

NOTE: The foster child/adult or relative care child cannot participate as a separate AU.

| Homeless Individual
a| An individual who will imminently lose their nighttime residence, lacks a fixed and regular nighttime residence, or  whose primary nighttime residence meets one of the following below:

* a halfway house or similar institution that provides a temporary residence for individuals intended to be institutionalized
* a temporary accommodation for not more than 90 days in the residence of another individual;
* a place not designed for, or ordinarily used, as a regular sleeping accommodation for human beings; (a hallway, a bus station, a lobby, or similar places);
* a supervised shelter designed to provide temporary accommodations for homeless individuals

NOTE:  Imminently homeless is defined as those who are due to lose their primary nighttime residence within 14 days, do not have an alternative residence, and lack the resources to secure permanent housing.

Homeless AUs may use benefits to purchase prepared meals from homeless meal providers and other eating facilities authorized by FNS.

| Institutional Care Residents
a| Individuals shall be considered residents of an institution when the institution or facility provides the majority of their meals (over 50 percent of three meals daily) as a part of the institution's normal services.
Exclude from any AU.
Residents of institutional care are ineligible to participate in SNAP except for residents living in one of the following:

* battered women and children's shelters
* drug addiction or alcohol treatment centers
* group living arrangements for disabled or blind individuals
* homeless shelters
* federally subsidized housing for the elderly.

NOTE: The residents of the above five types of institutional care may receive benefits even if over 50 percent of three meals are provided daily by the facility.

Refer to xref:3215.adoc[]; xref:3220.adoc[];
xref:3225.adoc[]; and xref:3230.adoc[].

| Live-in Attendants
a| Determine eligibility as a separate AU for the individual(s) whose presence in the home is solely for medical care, housekeeping, childcare or similar reasons.

NOTE: Do not include the attendant in the AU with those for whom s/he provides services.

| Non-resident Participants of Drug and Alcohol Treatment Centers
| Individuals who regularly participate in a drug and/or alcohol treatment program but who do not live in a treatment center.

Verify the participation of the AU member in the treatment program.

Determine the eligibility of the AU in which the participant resides, using normal SNAP policies.

During treatment sessions, the participant may use benefits to purchase prepared meals from the center/program.

Refer to xref:3220.adoc[], for policy regarding individuals who *reside* in treatment centers.

| Roomers
| Determine eligibility as a separate AU for those individuals who are furnished lodging, but not meals, for compensation.
A roomer cannot be included as a member of the AU providing lodging.

| Seasonal Farm Workers (migrant or non-migrant)
a| An AU is a migrant or seasonal farmworker AU if at least one adult member of the AU meets the criteria. Destitute migrant or seasonal farm worker AUs are entitled to expedited processing.
Seasonal farm workers are individuals who meet the following criteria:

* They are engaged in seasonal work related to an agricultural crop.
* They are hired on a temporary basis.

Refer to xref:3235.adoc[], for special considerations.

| Strikers
| Determine the eligibility of an AU that includes a striker based on the AU's eligibility status on the day before the strike.
Refer to xref:3240.adoc[].

| Students
| Students in institutions of higher education are included in the AU if they meet the eligibility requirements for a student.
Refer to xref:3245.adoc[].

| Teen Parent Improvement Program (TPI) Residents
| Residents of TPI residential homes may be eligible for SNAP benefits as separate one-person assistance units.
If the child(ren) of the teen lives with the teen in the residential home, the teen may receive for her children and herself.

|===
