= 3210 Categorical Eligibility
:chapter-number: 3200
:effective-date: January 2025
:mt: MT-80
:policy-number: 3210
:policy-title: Categorical Eligibility
:previous-mt-number: MT-79

include::partial$policy-header.adoc[]

== Requirements

Households in which ALL assistance unit (AU) members receive TANF, Work Support Payments (WSP), or Supplemental Security Income (SSI) are categorically eligible to receive Supplemental Nutrition Assistance Program (SNAP) benefits.
Categorical eligibility is expanded to include all households in which any member receives or is authorized to receive, TANF Community Outreach Services (TCOS).

== Basic Considerations

=== TANF/SSI Categorical Eligibility

Categorical eligibility begins the month in which all AU members are certified for TANF cash assistance, Work Support Payments (WSP), or SSI.

Categorical eligibility continues if TANF, WSP, or SSI benefits are recouped, suspended, or authorized but not received because the AU is eligible for less than the monthly minimum payment amount for those programs.

=== TCOS Categorical Eligibility

Categorical eligibility is expanded to include households containing any members that receive or benefit from, TANF Community Outreach Services (TCOS).

TCOS provides information and referral services to households whose income falls at or below 130% of the federal poverty level (FPL) or to households whose income falls at or below 200% of the FPL if *all adult* AU members are elderly or disabled.

Eligibility for TCOS is determined prior to a SNAP eligibility determination.

To initially establish eligibility for TANF Community Outreach Services, the household's statement of gross income is accepted.

The signatures of all SNAP applicants who apply or recertify for benefits (including those who also apply or recertify for TANF) will be obtained on the Application for Benefits - Form 297, the xref:attachment$form-297a.pdf[Form 297A], or the SNAP/Medicaid/TANF Renewal Form 508, which acknowledges notification of TCOS eligibility. xref:attachment$form-524.pdf[TCOS Brochure] will be mailed to the applicants upon their request.


TCOS is discussed and explained to SNAP applicants during the interview. Information and referral services are discussed after eligibility for TCOS has been established.

Providing a verbal explanation of TCOS  and having the applicant's signature on the Application for Benefits, Form 297A, and/or the SNAP/Medicaid/TANF Renewal Form 508 establishes initial eligibility for TCOS.

*TCOS SNAP categorical eligibility does not continue for applicants or recipients if gross income, upon verification, is above the identified FPL.*


TCOS categorically eligible AUs must meet the non-financial eligibility criteria but are not subject to gross or net income limits.

The resources of TANF/SSI and TCOS categorically eligible AUs are excluded when determining eligibility for benefits.

TANF/SSI and TCOS eligible AUs do not have to provide verification of the following information to establish categorical eligibility:

* resources
* gross income
+
NOTE: Gross income is verified to establish net income and benefit levels, not categorical eligibility.
* Social Security numbers
* sponsored alien information
* residency

If any of these factors are questionable, verify according to normal processing standards.

A household *may be* considered categorically eligible if it contains the following ineligible members;
however, these members cannot be included in the AU.

* A member who is an ineligible alien
* A member who is an ineligible student
* A member who is an ineligible ABAWD (i.e. an ABAWD who has 3 countable months in the 36-month period and has not regained)
* A member who is ineligible because of failure to comply with work requirements
* A member who is SSN disqualified

=== Households Not Eligible for Categorical Eligibility

A household *is not* considered categorically eligible if:

* It contains an IPV disqualified member.

* The head of household is work sanctioned.
* The household has transferred resources to become eligible for benefits.
* It is an elderly/disabled household whose gross income exceeds 200% of the FPL.
* It is a regular SNAP household whose gross income exceeds 130% of the FPL but it contains an elderly or disabled AU member.
* It is the first-time reapplying for SNAP benefits after losing eligibility for substantial winnings from lottery, gambling, prizes, awards and/or windfalls that exceed $4500;
eligibility is determined under regular SNAP rules, which considers resources.
This requirement is not permanent and only applies to the first time a household is certified and determined eligible following the loss of eligibility for substantial winnings from lottery, gambling, prizes, awards and/or windfalls of more than $4500.

Eligibility staff are expected to take the following steps for households reapplying after losing eligibility due to lottery and gambling winnings in excess of $4500 prior to determining eligibility:

* Discuss, document, and *update* the household's remaining liquid resources on the *Liquid Resources - Details* page.
* If the AU reports liquid resources that exceed 75% of the applicable resource limit, third party verification of liquid resources is required.
(Acceptable forms of verification include bank statements and online bank statements (received within the last 30 days), check stubs, written statements, or current documentation on a Financial Institution's letterhead/stationary, etc.)
* The AU is potentially eligible to receive SNAP benefits, *if* the AU's resources are below the resource limit for their AU type.

[caption=Exception]
NOTE: If the household contains an *IPV* disqualified member, the resources of the entire household are excluded.

Apply the gross and net income limits and *do not count* the disqualified member or any AU member's resources in the budget when determining eligibility for the AU.

Benefit allotment levels will be based on the net income limits after all income and deductions are verified and applied.

NOTE: Categorically eligible one and two member AUs will receive the minimum benefit allotment even if their income is over the net income limit.

=== Benefit Allotment Levels TANF/SSI and TCOS

Categorically eligible AUs of three or more individuals whose income is above the net income limit will not receive benefits.
The Gateway system will automatically close these cases.
