= 3345 SNAP E&T Work Requirement Overview
:chapter-number: 3300
:effective-date: December 2023
:mt: MT-76
:policy-number: 3345
:policy-title: SNAP E&T Work Requirement Overview
:previous-mt-number: MT-68

include::partial$policy-header.adoc[]

== Requirements

Recipients of SNAP benefits may volunteer to participate in the SNAP Employment & Training (E&T) program. The name of Georgia's SNAP E&T Program is the SNAP Works Program.

== Basic Considerations

DFCS collaborates with community-based organizations (CBOs), workforce development programs, providers of basic education, and short-term vocational training programs. This will help to ensure that SNAP Works eligible participants have access to the work training activities needed to achieve the goal of self-sufficiency by gaining self-sustaining employment.
Those participants who successfully complete the work program will become less reliant on public State and/or Federal assistance programs.

=== Objectives

The SNAP Works Program (e.g., the Employment and Training Program in Georgia) has the following objectives:

* to promote self-sufficiency through a combination of employment, education, training and work support services,

* to promote the value of work,

* to assist participants in obtaining full-time employment as quickly as possible,

* to develop partnerships with the business community to ensure that applicants and recipients have real opportunities for job placement,

* to assess the job market to ensure that recipients are prepared for jobs available in their community and to take advantage of employer expansion,

* to expand the supply of and increase the participant's access to employment, education, training, and support services resources,

* to refer participants to resources to meet needs which cannot be addressed by DFCS,

* to provide leadership in effective collaboration among local education, training, and support services providers for the benefit of the participant,

* to provide necessary work support services to recipients participating in the SNAP Works Program.

=== Legislative Authority

The Personal Responsibility and Work Opportunity Reconciliation Act of 1996 and the Balanced Budget Act of 1997 are the legislative authorities for the Food Stamp Employment and Training Program.

=== Administrative Structure

The Department of Human Services (DHS), Division of Family and Children Services (DFCS) is administratively responsible for implementation and ongoing E&T program operations.
Services are provided through a case management system, which recognizes differing client needs and coordinates needed services with various programs and agencies.

=== SNAP E&T Case Management

Case Management focuses on fostering self-sufficiency and eliminating dependency on public assistance.
The process communicates to the participant the expectations to overcome dependency, provides support services and strengthens motivational skills and the capacity to become self-supporting.
The Case management process is goal-oriented, and participant centered.
It builds upon the strengths of the participant and empowers the participant to act on his/her own behalf.

=== Case Management Definition

Case management functions include the following:

* assessing a participant's skills, aptitudes, strengths, interests, and social service needs,

* developing a Individual Employment Plan (IEP) with each participant,

* maximizing the participation of each participant to assist in obtaining employment as quickly as possible,

* developing/reinforcing the participant's skills in planning for self-sufficiency,

* arranging and coordinating services to carry out the Individual Employment Plan (IEP),

* evaluating and monitoring the performance of both the participant and the service provider,

* coordinating services within and across organizations,

* identifying insufficient resources and assisting in devising solutions.
