= 3405 Resources
:chapter-number: 3400
:effective-date: June 2026
:mt: MT-87
:policy-number: 3405
:policy-title: Resources
:previous-mt-number: MT-79

include::partial$policy-header.adoc[]

== Codes and References

7 CFR § 273.8

== Requirements

Resources are assets accessible to the Assistance Unit (AU), which can be converted to cash to meet daily living expenses.
These assets must be taken into consideration in determining eligibility.

== Basic Considerations

AUs that are categorically eligible do not have to meet the Supplemental Nutrition Assistance Program (SNAP) resource limits.
All SNAP AUs that receive TANF, SSI, or TANF Community Outreach Services (TCOS) do not have to meet the resource requirements to receive benefits.

The SNAP's resource policy is the same as the TCOS resource criteria, which excludes non-liquid resources from the eligibility determination.
Refer to xref:3210.adoc[] for policy regarding categorically eligible AUs.

Liquid resources are counted for AUs that [.underline]#are not# categorically eligible for SNAP.
The resource limit for AUs that contain at least one AU member aged 60 or older or disabled per SNAP policy is $4,500.
The resource limit for all other SNAP AUs is $3,000.

To determine eligibility based on resources, the following series of questions must be resolved:

* What is the resource limit for the AU?
* Whose resources are considered?
* Who owns the resource?
* Is the resource accessible to the AU to meet its needs?
* Is the resource countable?
* What is the value of the resource?
* Has the AU transferred any resources in order to become eligible?

Resources are considered liquid or non-liquid and are described as follows:

* Liquid resources are resources such as bank accounts, which can be converted easily to cash and are accessible for daily living expenses.

Resources that are accessible to an AU are used to determine eligibility at the following times:

* application
* recertification (renewal)
* periodic reporting

=== Consideration of Resources

The countable resources of the following individuals are used to determine eligibility:

* eligible AU members
* ineligible aliens
* lawbreakers
* disqualified individuals
* enumeration-sanctioned individuals
* work-sanctioned individuals
* ineligible Able-Bodied Adults Without Dependents (ABAWDs)

NOTE: A portion of the resources of a sponsored alien is used to determine eligibility.
Refer to xref:3630.adoc[].

=== Ownership of the Resource

It is assumed that a resource belongs to the individual in whose name it is listed unless the AU can prove otherwise.
The burden of proof in establishing that a resource does not belong to an individual rests with that AU.
Convincing evidence such as the following must be provided to rebut ownership:

* statements from other individuals in a position to substantiate the AU member's claims
* legal documents which substantiate the claim.

=== Jointly Owned Resources

A resource that is jointly owned by a non-AU member is considered accessible in its entirety to the AU, unless the AU claims inaccessibility.
The portion of a resource owned by a non-AU member is not automatically excluded.

To verify inaccessibility, the AU must do the following:

* Verify that the resource is not entirely owned by the AU and show that the resource is used for the non-AU member's benefit.
* Verify the inability to dispose of or sell the resource without the consent of the non-AU member.

Based on the information and verification provided by the AU, the Eligibility Specialist (ES) determines the accessibility of a resource.

[caption=Exception]
NOTE: If the resource is jointly owned by an AU member who receives SSI or TANF, the AU must verify that the resource does not belong to the entire AU.
If that is the situation, exclude the portion of the jointly owned resource that belongs to the AU member who receives SSI or TANF.

=== Accessibility of Resources

A resource is considered accessible when the AU has the legal ability to liquidate the resource and to use the proceeds.

Resources that are inaccessible to the AU or which the AU cannot legally liquidate are excluded.

Examples of resources excluded due to inaccessibility include the following:

* security deposits on rental property or utilities
* a property in probate
* real estate that the AU is making a good faith effort to sell
* resources jointly owned by women or children in battered women's shelters and whose former AU members, if accessible, are dependent on the agreement of the joint owner who still resides in the former residence
* any funds in a trust or transferred to a trust, and the income produced by that trust to the extent it is not accessible to the AU
* a trust arrangement that is not likely to cease during the certification period, and no AU member has the power to revoke the trust arrangement or change the name of the beneficiary during the certification period
* the trustee administering the funds is either:
** a court, institution, corporation, or organization which is not under the direction or ownership of any AU member
+
*or*
** an individual who has court-imposed limitations placed on the use of the funds
+
*and*
** the trust investments made on behalf of the trust do not directly involve or assist any business or corporation under the control, direction, or influence of an AU member
+
*and*
** the funds held in an irrevocable trust are established from the AU's own funds, if the trustee uses the funds solely to make investments on behalf of the trust or to pay educational or medical expenses of any person named by the AU creating the trust
+
*or*
** established from non-AU funds by a non-AU member.
Refer to <<trusts,Trusts>> in Chart 3405.1, Types of Resources.

NOTE: This list is not all-inclusive.

=== Resources Affected by Bankruptcy

Bankruptcy is a legal process to help people who owe money, or debtors, get relief from debts they cannot pay and, at the same time, help people who are owed money, or creditors, get paid from assets or property the debtor has. The debtor's remaining property is administered and distributed to his/her creditors.

The AUs' resources are included or excluded depending on their accessibility and the AUs' ability to liquidate the resource and retain the proceeds.

=== Countable Resources

Only those resources that are accessible to the AU at the time that eligibility is being determined are counted.

<<chart-3405-1,Chart 3405.1 Types of Resources>>, indicates whether a specific resource is included or excluded in the eligibility determination.

Do not count as a resource income that has been included in the SNAP budget for that month.

Excluded income that is retained as a resource is counted as a resource.

=== Resources with Significant Return

The entire value of a resource is excluded if the AU is unable to sell it for any significant return.
Significant return is defined as any return, after estimated costs of sale or disposition, taking into account the ownership interest of the household, that is estimated to be more than $1,500.

[caption=Exception]
NOTE: This exclusion does not apply to stocks, bonds, and negotiable financial instruments.

=== Commingled Resources

Commingled resources are assets or funds from different sources mixed together into a single account. Excluded resources may be commingled with countable resources.
If so, the excluded resource retains its exclusion for six months from the date the resources were commingled.
After six months, the commingled assets are counted in their entirety.

=== Conversion of Resources

If an excluded resource is converted to a countable resource, the value of the resource is applied to the resource limit in the month the resource is converted.

[caption=Exception]
NOTE: Proceeds from the sale of capital goods are considered income.
Refer to xref:3420.adoc#chart-3420-2[Chart 3420.2, Types of Income].

If a countable resource is converted to cash, the value of the cash is countable toward the resource limit.

NOTE: The resource must be sold for Fair Market Value (FMV), or the AU may be subject to disqualification under the transfer of resources policy.

=== Transfer of Resources

A transfer of resources for the purpose of this policy includes selling, swapping, trading, or giving away a countable resource for less than the FMV.

A transfer of resources knowingly for the purpose of becoming or remaining eligible for benefits can result in the disqualification of the entire AU.

The transfer of resources policy applies to all AU members, including lawbreakers and ineligible, sanctioned, or disqualified members whose resources are considered in the eligibility determination.

A disqualification penalty is applied to the AU if any resource is transferred at the following times:

* during the three months immediately preceding the date of application
* any time during the certification period.

The disqualification penalty begins with the date the Eligibility Specialist (ES) discovers the AU has transferred resources to qualify for benefits.
Determine the begin date for the disqualification penalty as follows:

|===
^| IF ^| THEN

| The ES discovers the AU has transferred resources at initial application,
| The disqualification period begins with the month of application.

| The ES discovers the AU has transferred resources during the certification period,
| The disqualification begins with the month following the month in which the timely notice period expires.
A notice is sent to the AU explaining the reason for and the period of the disqualification.
|===

A disqualification is not applied if the transfer meets one of the following criteria:

* The total amount of countable and transferred resources does not exceed the applicable resource limit for the AU.
+
*OR*

* The resource was sold or traded at or near Fair Market Value.
+
*OR*

* The transfer occurred between SNAP AU members, including ineligible or disqualified members.
+
*OR*

* The resource was transferred for reasons other than qualifying for SNAP, such as establishing an educational trust fund or paying off bills.

=== Determining the Disqualification Period for Transfer of Resources

Follow the steps below to determine the length of a disqualification period resulting from a transfer of resources:

[horizontal,labelwidth=10]
Step 1:: Add the value of the transferred resource to other countable resources.

Step 2:: Subtract the appropriate resource limit.

Step 3:: Use the excess amount to determine the length of disqualification as follows:
+
[cols="3,^2",width=75%]
|===
^| Amount transferred in excess of the resource limit | Period of disqualification

| $0 - $249.99
| 1 month

| $250 - $999.99
| 3 months

| $1000 - $2999.99
| 6 months

| $3000 - $4999.99
| 9 months

| $5000 and up
| 12 months
|===

Step 4:: Notify the AU of the disqualification, the time period it covers, and when the AU may reapply for benefits.

=== Value of a Resource

The value of a resource is determined by using one of the following:

* cash value (CV)
* fair market value (FMV)
* equity value (EV)

=== Cash Value (CV)

Cash value is the amount accessible to the AU if the resource is converted to U.S. funds.
In some cases, a penalty may be applied for early withdrawal of funds.
The amount of the penalty is deducted from the value of the resource to determine the cash value accessible to the AU.

=== Fair Market Value (FMV)

Fair market value is the amount that the item can sell for on the open market in the geographic area involved.

=== Equity Value (EV)

Equity value is the FMV less legal debt or encumbrances.

=== Verification of Debt or Encumbrances

The AU's statement may serve as proof of legal debt or encumbrance if it is clear, consistent, and concise.
The AU's statement must identify the property and contain the current payoff amount.
If the AU's statement is questionable, obtain third-party verification.

NOTE: An encumbrance is a claim, restriction, or liability attached to a property (like a house or land) held by someone other than the owner. It acts as a burden that limits how the owner can use the property or affects its transferability, such as a mortgage or lien.

=== Determining the Value of Resources

The most current available information is used to verify the value of a resource in determining eligibility.

Sources which may be used to determine value include the following:

* bank record
* deeds
* property records
* tax records
* insurance policies
* stock quotes in newspapers
* statements from individuals in a position to verify the value of a resource

NOTE: This list is NOT all-inclusive.

=== Determining Appreciation/Depreciation

The appreciation or depreciation of a non-liquid resource is considered in determining the resource value.

== Procedures

Follow the steps below to determine whether the AU meets the resource limit.

=== Determining Eligibility for Resources

[horizontal,labelwidth=10]
Step 1:: Determine whose resources must be considered.

Step 2:: Determine if the resources are accessible to the AU.

Step 3:: Determine if the resource must be counted.

Step 4:: Calculate the total countable resources.
+
--
If the total countable resources are less than or equal to the resource limit, approve or continue benefits.

If the total countable resources exceed the resource limit, deny or terminate benefits.
--

=== Verification

Third-party verification of liquid resources is required when the value of the countable resources exceeds 75% of the applicable resource limit.

Acceptable forms of verification include bank statements and online bank statements (received within the last 30 days), check stubs, written statements, or current documentation on a Financial Institution's letterhead or stationery, etc.

Liquid and non-liquid resources owned by a TANF or SSI recipient, a household receiving TCOS services, and any resources that are [.underline]#excluded# by policy in the SNAP budget have no verification requirement.

For all other countable resources, accept the AU member's statement for the type and value, provided it is less than 75% of the resource limit, unless the information provided is questionable and/or conflicts with other information available to the agency.

The chart below lists resources alphabetically and provides the following information:

* source/type of resource
* description of the resource
* whether the resource is liquid or non-liquid
* the value to consider: cash value (CV), equity value (EV), or fair market value (FMV)
* whether the resource is included (I) or excluded (E) in the eligibility determination

Included means it is counted in the SNAP budget; excluded means it is not.

NOTE: When the resource is excluded, the liquid/non-liquid indication may be omitted in the chart below.

.CHART 3405.1 TYPES OF RESOURCES
[#chart-3405-1,cols="2,4,^"]
|===
^| SOURCE / TYPE ^| DESCRIPTION / VALUE TO CONSIDER | I / E

| Achieving a Better Life Experience (ABLE) / STABLE Accounts

Liquid
| A tax-advantaged savings account to which contributions can be made to meet the qualified disability expenses of the owner or designated beneficiary
| E

| AGENT ORANGE PAYMENTS

Liquid
| Money retained from a payment made to a Vietnam Veteran who was exposed to Agent Orange and to the surviving spouse and children of a deceased Vietnam Veteran exposed to Agent Orange.
| E

| ANNUITIES

(Supplemental Retirement Plans)

Liquid
a| An investment plan.
It can be established as a supplemental retirement plan through an insurance company or other investment source.

[caption=Exception]
NOTE: Exclude if termination of employment or retirement is required for access and employment continues.

If employment ends and the funds are accessible to the AU, count it as income in the SNAP budget.

NOTE: If recurring payments are made from the annuity, Refer to xref:3420.adoc[].

Count the CV.
| I

| BONDS

Liquid
| Government-issued interest-bearing certificates redeemable on a specific date, such as U.S. savings bonds, municipal bonds, etc.

Count the CV.
| I

| BURIAL CONTRACTS AND BURIAL INSURANCE

Liquid
a| Prepaid contracts to cover funeral expenses or an insurance policy specifically designed for burials.

NOTE: The funeral home is usually named as the beneficiary of the insurance policy.

If it is not accessible, totally exclude.
| E

| BURIAL PLOTS

Non-Liquid
| One burial plot per AU member

Use the EV for each additional plot and count toward the resource limit.
| E

| CASH

Liquid
| Money on hand

Count cash value less any money considered income in that month.

Use the CV.
| I

| CASH BALANCE PLAN IRS Code 401(a)

Liquid
| Employer-based “hybrid” plan that combines features of a defined benefit and defined contribution plans.
The person may be allocated an account, but the account balance accrues at a specified rate.
The account does not depend on investment performance.
| E

| CERTIFICATES OF DEPOSIT (CD)

Liquid
| Certificate representing a specific sum on deposit with a financial institution, which accrues interest over a set period of time, less any penalties for early withdrawal

Use the CV.
| I

| CHECKING ACCOUNTS

Liquid
a| An account on which checks, ATM withdrawals, etc.,
may be written against amounts on deposit

Use the CV less any money considered income in that month.

[caption=Exception]
NOTE: Refer to Jointly Owned Resources in this section.
| I

| COIN COLLECTIONS

Liquid
| A collection of coins.

Use the face value of the coin collection as the cash value.
| I

| COMMINGLED FUNDS

Liquid
| The mixing of funds that belong to one party and funds belonging to another party.

| I

| CREDIT UNION ACCOUNTS

Liquid
| Money on deposit with a cooperative organization with the functions of a bank.

Use the CV less any money considered income in that month.
| I

| CRIME VICTIM COMPENSATION PROGRAM

Liquid
| Money retained from payment through federal or federally funded state or local programs that cover costs incurred by victims of crime.
| E

| CROWD FUNDING ACCOUNTS

Liquid
| An online platform that allows individual donors to fund specific campaigns for charity, individuals in need, projects, and business ventures.
Ex: GoFundMe, Kickstarter, Indiegogo.
The funds are counted as liquid resources at the point they become accessible to the AU.
| I

| DEFERRED COMPENSATION PLANS

Liquid
a| Funds held in a salary reduction retirement place.
The funds are excluded as long as they remain in the plan.

NOTE: If the funds are withdrawn then, the withdrawal amounts may be counted as countable resource or income.
For income, refer to RETIREMENT OR PENSION in to xref:3420.adoc[].
| E

| DISASTER RELIEF ACT OF 1974 AND EMERGENCY ASSISTANCE ACT OF 1988

Liquid
| Any governmental (federal, state, local) payments that are designated for the restoration of a home damaged in a major disaster or natural catastrophe.
This includes governmental payments to save lives, protect property and public health and safety, or to lessen or avert the threat of a catastrophe or major disaster.

Includes loans and grants from the Federal Emergency Management Assistance (FEMA), payments made by the Department of Housing and Urban Development, disaster loans, family grant programs, and grants made by the Small Business Administration as a result of disasters.
| E

| EARNED INCOME TAX CREDIT (EITC)

Liquid
a| Tax credit that is received in one of the following ways:

* advanced payments - tax credits received as part of the regular paycheck
* non-recurring lump sum - tax credits received in the form of an income tax refund

*If the AU member received SNAP benefits at the time of receipt and continued to receive benefits for a 12-month period, exclude the EITC for 12 months from the month of receipt.
Include any remainder as a resource in the 13th month after receipt.

If the AU did not receive SNAP benefits at the time of receipt, exclude the money in the month of receipt and the following month for the individual and the individual's spouse.
| E

| EMPLOYEE STOCK OWNERSHIP PLAN IRS Section Code 401(a)

Liquid
| An organized plan for employees to buy shares of their company's stock.
Distributed benefits must be offered in the form of the company's stock.
| E

| EMPLOYMENT INTERVENTION SERVICE

Liquid
| Lump sum payment used as short-term assistance that is equivalent to four times the maximum TANF grant amount for the AU size.
| E

| EDUCATION ACCOUNTS

Liquid
| A Section 529 account is an education savings plan account operated by a state or educational institution designed to help families set aside funds to pay for future college costs.

A Coverdell education savings account is a savings account that allows parents, grandparents, and others to contribute cumulatively for the education expenses of a child.
Contributions are not tax-deductible, but withdrawals are.
| E

.2+| ENERGY ASSISTANCE OTHER THAN LIHEAP

Liquid
| Monies retained from payments or allowances made under any federal, state, or local law for the purpose of energy assistance.
| E
| Federal or State one-time assistance for weatherization or emergency repair or replacement of heating or cooling devices.
^| I

| FEDERAL THRIFT SAVINGS PLAN
(Section 8439 of Titles 5 USC)

Liquid
| A retirement savings and investment plan offered by the federal government to its employees.
| E


| GIFT CARD

Liquid
| A card that typically functions like a debit card and can be used for a specified cash value for goods and/or services at businesses.
| E

| GRANDPARENTS RAISING GRANDCHILDREN INTERVENTION SERVICES

Liquid
| TANF lump sum payment in the amount of three times the eligible grant amount for the AU size.

This payment is used to help pay for the cost of emergency needs incurred by the grandparents when the children come to live with them.
| E

| HOME PLACE

Non-Liquid
| The home and surrounding land occupied by the AU, if not separated by intervening property owned by others.

A lot/partially built home that the AU owns, or a lot being purchased on which to build or place a permanent home, provided the AU does not own another home place.
Refer to xref:3415.adoc[], for additional information.
| E

| HOUSEHOLD/ PERSONAL GOODS

Non-Liquid
| Household and personal effects or other belongings such as furniture, appliances, clothing, personal items, or items required because of a disability.
| E

| HOUSEHOLD ITEMS OF UNUSUAL VALUE

Non-Liquid
| Items such as expensive silver, jewelry, stamps, guns, or other such collections.
| E

| INCOME TAX REFUND

Liquid
| Monetary refunds paid to taxpayers from the state or federal government.

Count the total amount of the refund if the household does not meet categorical eligibility criteria.
Refer to xref:3210.adoc[].

If the refund is a check for a jointly filed tax return, refer to Jointly Owned Resources in this section.

If any portion of the refund includes EITC, refer to the Earned Income Tax Credit (EITC) in this section.
| I

| INDIAN/ALASKAN NATIVE PAYMENTS

Liquid
a| Payments to Native Americans based on federal statutes.

Examples of these statutes include, but are not limited to, the following:

* Alaska Native Claims Settlement Act
* Sac and Fox Indian Claims
* Indian Tribal Payments under PL 94-114, Section 6
* Grand River Band of Ottawa Tribal payments under PL 94-540
* Public Law to the Confederated Tribes and Bands of the Yakima Indian and Apache Tribe of the Mescalero
* Payments made under the Maine Indian Claims Settlement Act of 1980
* Navajo or Hopi Indian pursuant to PL 93-531
* Indian Child Welfare, Public Law 95-608
| E

.2+| INDIVIDUAL DEVELOPMENT ACCOUNT (IDA)

Liquid
| An account established by or on behalf of a TANF A/R for post-secondary educational expenses, the first purchase of a home, or to start a new business.
Exclude funds up to $5000, including funds withdrawn and used for the stated purpose.
| E

| At the point the owner of the IDA is no longer a TANF recipient, the IDA becomes a countable resource.
^| I

| INDIVIDUAL RETIREMENT ACCOUNT (IRA)

(IRS Code Section 408)

Liquid
a| An investment account or annuity in which a person can set aside income up to a specified amount each year and usually deduct the contributions from taxable income, with the contributions and interest being tax-deferred until retirement.
The account is controlled by an individual rather than an employer.

NOTE: If the plan is owned by more than one person, refer to Jointly Owned Resources in this section.
| E

| INDIVIDUAL RETIREMENT ACCOUNT (IRA) ROTH/MyRA

(IRS Code Section 408A)

Liquid
| An investment account or annuity in which a person can set aside income each year, but usually cannot deduct the contributions from taxable income.
| E

| INDIVIDUAL RETIREMENT ACCOUNT (IRA) SIMPLE RETIREMENT ACCOUNT

IRS Code Section 408(p)

Liquid
| A plan that gives small employers a simplified method to make contributions toward their employees' retirement and their own retirement.
Employees may choose to make salary reduction contributions, and the employer makes matching or non-elective contributions.
All contributions are made directly to an Individual Retirement Account or Individual Retirement Annuity (IRA) set up for each employee.
This type of plan is available only to small businesses.
| E

| INSTALLMENT CONTRACTS / AGREEMENTS (for sale of land or buildings)

Non-Liquid
a| A written agreement with specific stipulations for the sale of land or buildings, and the contract/agreement produces income consistent with its FMV

NOTE: The property sold under the contract or held as security in exchange for a purchase price consistent with the FMV of that property is also excluded.
| E

| KEOGH PLAN

IRS Code Section 401(a)

Liquid
| A tax-deferred pension plan for employees of unincorporated businesses or for self-employed persons.
Consider the total CV of the funds in the retirement plan, minus the early withdrawal penalty.
| E

| KEOGH PLAN

(owned with others) IRS Code Section 401(a)

Liquid
| A retirement plan.
If the plan contains a contractual agreement with an individual whose resources are not considered in determining eligibility, the funds are considered inaccessible to the AU.
| E

| LIFE INSURANCE

Liquid
| An insurance policy that pays a beneficiary on the death of an individual
| E

| LIFE INTEREST

Non-Liquid
| Property that an individual has a right to use but not dispose of during his/her life

Consider any income received from the property.
| E

.2+| LIVESTOCK

Non-Liquid
a| Animals owned for the following purposes:

* raised solely for the purpose of feeding AU members
* producing income that is consistent with its FMV
* used to assist a disabled individual
| E

a|
* not producing income consistent with the FMV
* used for recreational purposes, and no income is derived
* Count the EV

NOTE: Refer to the policy at the beginning of this section for treatment of non-liquid resources owned by categorically eligible households.
^| E

| LOANS FROM OTHERS

Liquid
| Money received by the AU that the AU has an obligation to repay
| E

| LOANS TO OTHERS (NOTES RECEIVABLE)

Liquid
| Monies loaned to persons outside the AU where a repayment agreement exists

Count the CV of any money owed to the AU.
| I

| LOTTERY WINNINGS, GAMBLING WINNINGS, PRIZES, AWARDS, AND/OR WINDFALLS

Liquid
| A sum of money received as a result of a winning ticket or other monetary gains in a game of chance.

Budget as income in the first ongoing month after receipt and as a resource ongoing.
| I

| LOW INCOME HOME ENERGY ASSISTANCE PROGRAM (LIHEAP) PAYMENT

Liquid
| Payments for home energy provided to, or indirectly on behalf of, an AU
| E

| LUMP SUM PAYMENTS

Liquid
| Money retained as a result of a lump sum that is not expected to recur, i.e. rebates, retroactive or corrective payments for prior months, insurance settlements, federal or state tax refunds

Count cash value.
AUs ineligible because of a lump sum must be given an opportunity to update the current resource amount.
| I

.3+| LUMP SUM/SSI BACK PAYMENTS

Liquid
| Money retained for payment of previous SSI benefits owed and paid to an individual who is currently receiving SSI.
| E

| Payment for previous SSI benefits owed and paid to an individual who is no longer receiving SSI
^| I

| Paid in installments.
Refer to xref:3420.adoc#chart-3420-2[Chart 3420.2, Types of Income].
^| E

| MONEY PURCHASE PENSION PLAN

Liquid
| A retirement plan in which a fixed amount or percentage of money is set aside each year by a company for the benefit of the employee.
Restrictions apply as to when and how the funds may be withdrawn without penalties.
| E

| NON-HOME PROPERTY

Non-Liquid
| Buildings and lands which are owned by the AU and not considered part of the home place

Refer to xref:3415.adoc[].
| E

| PASS ACCOUNT

(Plan to Achieve Self-Sufficiency)

Liquid
a| Money deposited in a bank account to be used for an SSI individual in a plan for self-sufficiency approved by the SSA

NOTE: The interest earned from a PASS account is disregarded as income.
| E

| PENSION/RETIREMENT PLANS

Liquid
a| A retirement plan provided by an employer.
The funds in the plan are excluded as resources by the Food and Nutrition Act of 2008, as amended by the Farm Bill 2008.

Plans include 401(a) plans, 401 (k) plans, 403 (a), 403 (b), 408, 408 (k), 408(p), 408(A), 457(b) plans, 501(c) (18) plans, and the Federal Thrift Savings Plan.

NOTE: If the funds are withdrawn, the withdrawal amounts may be considered countable resources or income.
For policy regarding income, refer to PENSION OR RETIREMENT income in to xref:3420.adoc[].
| E

| PROFIT-SHARING PLAN

IRS Code Section 401 (a)
| A retirement plan in which the contributions are made solely by the employer.
Employer contributions may be linked to profits, but not necessarily.
Employees get a share of the company's profits.
| E

| PUBLIC LAW 103-286

Liquid
| Money retained from payments to individuals received as a result of their status as victims of Nazi persecution
| E

| REAL PROPERTY

Non-Liquid
| Refer to xref:3415.adoc[].
| E

.2+| RENTAL PROPERTY

Non-Liquid
| Real property rented to others that annually produces income consistent with the FMV

Refer to xref:3425.adoc[], for Treatment of Income from Rental Property.
| E
a| For real property rented to others that does not annually produce income consistent with the FMV, consider the EV.

NOTE: Refer to policy at the beginning of this section for treatment of non-liquid resources owned by categorically eligible households.
^| E

.2+| RESOURCES OF AN SSI or TANF RECIPIENT

Liquid
a| An SSI recipient is a person who:

* has been approved to receive benefits
* receives benefits
* is approved for or receives benefits, but the benefits are suspended, being recouped because of an overpayment, or not paid because the amount is less than the maximum issuance amount.
| E

a| A TANF recipient is a person who:

* has been approved to receive benefits
* receives benefits,
* is approved for/receives benefits, but benefits are suspended, being recouped, or not paid because the amount is less than the minimum issuance amount.
^| E

| SAFE DEPOSIT BOX

Liquid
| Secure storage in a bank or other institution where money and other valuables may be deposited

Obtain a list of items that are in the box from the A/R.
Count the CV unless otherwise excluded.
| I

| SAVINGS ACCOUNTS

Liquid
| Monies held in a financial institution in an interest-bearing account

Count the CV
| I

.2+| SECURITY DEPOSIT ON RENTAL PROPERTY OR UTILITIES

Liquid
| Cash held by the provider and not accessible to the AU
| E

| Cash returned to AU.
It is counted in the month received
^| I

| SIMPLE 401(k) PLAN

IRS Code Section 401(a)

Liquid
| A qualified plan established by small businesses as a cost-efficient way to offer retirement benefits to their employees.
This type of 401(k) plan is available to employers with 100 or fewer employees.
| E

| 401(k) PLAN

IRS Code Section 401(a)

Liquid
| A qualified plan established by employers in which eligible employees may make salary reduction contributions on a post-tax or pretax basis.
| E

| ROTH IRA

Section 408A
| A retirement plan in which contributions are made with after-tax dollars and are not tax-deductible.
| E

| 403(a) PLAN

IRS Code Section 403(a)

Liquid
| A retirement plan available for any profit and non-profit employer.
For defined contribution plans funded with annuities, these plans are usually funded solely with employer contributions.
| E

| 403(b) PLAN

IRS Code Section 403(b)

Liquid
| A retirement plan available for non-profit organizations such as universities, some charitable organizations, and self-employed ministers.
| E

| SIMPLIFIED EMPLOYEE PENSION PLAN (SEP) IRS Code

Section 408(k)

Liquid
| A plan that allows a business to make contributions to a retirement plan for employees.
A SEP agreement is adopted by the company, and contributions are made directly to a traditional individual retirement account (IRA) or a traditional individual retirement annuity (SEP-IRA) set up for each employee.
Employers can deduct the amount of contributions made on behalf of employees from their taxes.
| E

| 457(b) PLAN

IRS Code Section 457(b)

Liquid
| A funded plan offered by state and local governments or an unfunded plan offered by non-profit organizations
| E

| 501(c) 18 PLAN

IRS Code Section 501(c) 18

Liquid
| A retirement plan for union members consisting of employee contributions to certain trusts, which had to be established by June 1959.
| E

| SPENDING ACCOUNT

Liquid
| Funds that are held in an account to pay certain expenses such as childcare or medical expenses
| E

| STOCKS

Liquid
| A certificate that verifies ownership of shares in a company.

Consider the CV.
Count the value of the stock at the time of the interview by verifying with the newspaper or a broker.
| I

| TRADITIONAL DEFINED BENEFIT PLAN

IRS Code Section 401

Liquid
| An employer-based retirement plan that promises retirees a certain benefit upon retirement, regardless of investment performance.
| E

.6+| [[trusts]]TRUSTS

Liquid
a| Any funds in a trust or transferred to a trust, and the income produced by that trust.

If the:

* trust arrangement can be revoked by an AU member
| I
a|* beneficiaries name can be changed during the certification period
^| I
a|* trust arrangement can cease during the certification period
^| I
a|* trustee administering the fund is a court, an institution, corporation, or organization which is not under the direction or ownership of any AU member
^| E
a|* trustee appointed by the court has court-imposed limitations placed on the funds
^| E
a|* trust investments made on behalf of the trust do not directly involve or assist any business or corporation under the control, direction, or influence of an AU member.

Refer to Accessibility of Resources in this section.
^| E

| UNIFORM RELOCATION ASSISTANCE AND REAL PROPERTY ACQUISITION

Liquid
| Reimbursements received under Public Law P.L. 91-646, Section 210
| E

| VEHICLES

Non-Liquid
| Vehicles are not countable resources.
| E

| WOMEN INFANTS & CHILDREN (WIC) SPECIAL SUPPLEMENTAL FOOD PROGRAM

Non-Liquid
| Vouchers which are redeemable for food items received by certain women and children considered to be nutritionally high risk.
| E
|===
