= 3415 Real Property
:chapter-number: 3400
:effective-date: November 2019
:mt: MT-57
:policy-number: 3415
:policy-title: Real Property
:previous-mt-number: MT-10

include::partial$policy-header.adoc[]

== Requirements

Property in the form of land and buildings is considered in determining the amount of resources to apply toward the resource limit.

== Basic Considerations

Property is generally categorized as one of the following:

* Homeplace
* non-income producing property
* income producing property

=== Homeplace

The home and surrounding property and outbuildings attached to the home are exempt from consideration as a resource.

To be considered a part of the homeplace, surrounding property cannot be separated by property owned by others.

If the A/R possesses a deed to the homeplace and s/he and another individual jointly own the land contiguous to the property, the contiguous property shall not be considered part of the homeplace.

Public rights of way, such as roads that run through the property do not affect the exemption.
The description of the property as contained in the deed shall be considered the homeplace.

The original homeplace may have been added to by purchase of land contiguous to the homeplace and more than one deed may exist.
These will be considered the homeplace provided all deeds are in the name of the A/R or the A/R's spouse.

Only one homeplace is exempt.

Buildings on the property such as stores or other houses that are not clearly part of the home and its outbuildings must be counted as a resource.

The homeplace remains exempt when temporarily unoccupied for the following reasons if the AU intends to return:

* employment
* training
* illness
* vacation
* uninhabitability caused by casualty or natural disaster.

=== Real Property Other Than a Homeplace

If an AU currently does not own a home, the value of a lot purchased to build a home is excluded.
A partially built home is also excluded if the AU currently does not own a home.

Real property includes the following:

* land
* lots
* trees on land
* all buildings which would pass to a buyer if the land or lots were sold
* mobile homes, whether occupied or unoccupied.

Value the property at equity value, fair market value less indebtedness.

Indebtedness is the total amount of debt that remains to be paid or the payoff amount.

Refer to xref:3405.adoc[] for policy regarding verification of indebtedness.

=== Sale of Real Property

If property is excluded, the proceeds are excluded during the month of sale.
Any proceeds remaining the month following sale are a resource.

If the property is counted as a resource, consider in the month of sale the income.
Any proceeds remaining the month following the sale are a resource.

=== Good Faith Effort to Sell

Exempt from consideration as a resource.
Any real property that the AU is making a good faith effort to sell at a reasonable price is exempt from consideration as a resource.

Good faith effort is defined as follows:

* actual sale attempt at a price not more than current market value and listing with a realtor or appropriate advertising such as newspaper, radio, etc.
* any bona fide offer must be accepted.

=== Property Related to Maintenance of an Excluded Vehicle

Exclude from consideration as a resource the value of that portion of real property that is directly related to the maintenance or use of a vehicle.

Exclude only the property or portion of property determined necessary for the maintenance and use of an income producing vehicle or a vehicle used to transport a physically disabled AU member.

=== Property Declared Unmarketable

Exclude from consideration as a resource property declared unmarketable by a competent authority.

Obtain verification of the reason the minimum price is not available from a competent authority.

=== Income Producing Property

Use the following definitions of income producing property:

* property which annually produces income consistent with its fair market value (FMV), even if only used on a seasonal basis.

* property, such as rental homes and farmland, which is essential to the employment or self-employment of a household member annually produces income consistent with FMV.

* rental homes which are used by households for vacation purposes at some time during the year which annually produce income consistent with their fair market value.

* installment contracts for the sale of land or buildings if the contract or agreement produces income consistent with its fair market value.
The value of the property sold under contract or held as security in exchange for a purchase price consistent with the fair market value of the property is also excluded.

Do not count income-producing property as a resource but count the income.
Refer to xref:3420.adoc[].

=== Producing Income Consistent with FMV

Determine if real property meets the definition of producing income consistent with the FMV as follows:

[horizontal,labelwidth=10]
Step 1:: Obtain verification from a reliable source to determine the average rate of return on a resource, as follows:

* the amount similar property would be leased for in the area for a similar purpose.
* the amount a similar resource would be expected to earn over a specific period of time.

Step 2:: Obtain the AU's records of the income the resource earned in the last year.

Step 3:: Compare the amount the AU's resource earned to the amount a similar resource is expected to earn.
+
--
If the AU's resource produces income equal to or exceeding the similar resource, it is considered to be consistent with the FMV.

If not, the resource is not considered income producing.
Therefore, the resource is a countable resource.
--

Use the following chart below to determine the resource treatment of specific types of real property.

[#chart-3415-1]
.CHART 3415.1 - REAL PROPERTY
|===
^| TYPE OF REAL PROPERTY ^| FS TREATMENT

| Homeplace - home and its outbuildings, and all surrounding property attached to the home.

Only one home and its outbuildings are exempt.
Other buildings and homes on the property are treated as property other than the homeplace.
| Exempt the value of the property.

| Home and surrounding property when unoccupied because of employment, training for employment, illness, vacations, uninhabitability caused by a casualty or natural disaster as long as the AU intends to return.
| Exempt the value of the property.

| Land purchased to build a home and the AU does not currently own a home.
| Exempt the value of the property.

| Land purchased to build a home and the AU currently owns a home.
| Count the equity.

| Property other than a homeplace which is *not* used as income producing property.
| County the equity.

| Property other than a homeplace which produces income consistent with its FMV.
| Exempt the value of the property.

| Property that the AU is making a good faith effort to sell at a reasonable price.

Verify that the AU has advertised the property for sale and has not declined a reasonable offer.
| Exempt the value of the property.
|===
