= 3425 Self-Employment Income
:chapter-number: 3400
:effective-date: November 2025
:mt: MT-85
:policy-number: 3425
:policy-title: Self-Employment Income
:previous-mt-number: MT-82

include::partial$policy-header.adoc[]

== Codes and References

7 CFR § 273.11

== Requirements

Income earned directly from one's own business or profession, rather than a specified salary or wages from an employer, is budgeted as self-employment income.

== Basic Considerations

Self-employment exists when there is no employer/employee relationship.
A self-employment determination is made by examining who has the right to control how, when and where the services are performed.

The AU member may be engaged in a business, service or profession rather than working as a salaried or waged employee such as an independent contractor, persons who sell Avon, or persons who own franchises.

=== Resources

Liquid resources used exclusively for a self-employment enterprise are considered unavailable to the AU.

=== Income

The total amount of self-employment income is determined by adding together all gross self-employment income (actual or anticipated) and capital gains income.

=== Capital Gains Income

Consider the total proceeds from the sale of capital goods or equipment, livestock, buildings, land, or machinery as capital gains income.

=== 40% Standard Deduction for Business Expenses

A 40% standard deduction for the cost of doing business is allowed if the AU establishes that it incurs at least one allowable cost of doing business.
Refer to <<chart-3425-1,Chart 3425.1>>.
Deduct 40% from the gross self-employment income to cover the expenditures related to the operation of a self-employment enterprise, if the AU incurs at least one allowable cost.

NOTE: Allow actual expenses at the AU's request.

If the AU member owns a business that is not incorporated and the AU member is the sole proprietor, any income the business earns is counted as countable gross income for the AU member.

If the AU member owns a business that is incorporated the gross countable income is the amount that the corporation pays to the AU member.

=== Types of Corporations

Certain businesses may be classified as partnerships, corporations, s-corporations, or limited liability corporations.

A *_partnership_* is a business organization in which two or more individuals join to manage and operate a business.
Each owner contributes money, property, labor, or skills and expects to share in the profits and losses of the business.

The following IRS forms may be used to verify income from a partnership:

* Form 1040 – U.S. Individual Income Tax Return
* Schedule K-1– Partner's Share of Income, Deductions, Credits, etc.
* Form 1065 – U.S. Return of Partner Income
* Schedule E – Supplemental Income and Loss
* Schedule D – Capital Gains and Losses
* Form 1099 –MISC – Miscellaneous Income (A business may use this form to report certain business transactions and certain income to the IRS)

A *_corporation_* is a legal entity that is separate and distinct from its owners.
The owner is considered an employee of the corporation and receives a salary.
The corporation pays taxes on the profits after all expenses such as salaries, bonuses, and overhead are paid.

The following IRS forms may be used to verify income from corporations:

* Form 1040 – U.S. Individual Income Tax Return
* Form 1120 - U.S. Corporation Income Tax Return
* Form 1120A – U.S. Corporation Short Form Income Tax Return
* Schedule E – Supplemental Income and Loss
* Schedule D – Capital Gains and Losses
* Schedule M-3 (Form 1120) Net Income (Loss) Reconciliation for Corporations with Total Assets of $10 Million or More

An *_S-corporation_* is a corporation that elects to pass corporate income, losses, deductions and credits to its shareholders for federal tax purposes.
Shareholders of S-corporations report their income and losses on their personal tax returns and are assessed taxes at their individual income tax rates.

S-corporations are responsible for the tax on certain built-in gains and passive income.

The following IRS forms may be used to verify income from S-corporations:

* Form 1040 – U.S. Individual Income Tax Return
* Form 1120 - U.S. Corporation Income Tax Return
* Schedule K-1– Partner's Share of Income, Deductions, Credits, etc.
* Schedule D – Capital Gains and Losses

A *_limited liability corporation (LLC)_* is a business structure allowed by state statute.
An LLC is similar to a corporation because the owners have limited personal liability for the debts and actions of the LLC.
The owners of an LLC are called members.
Members may include individuals, corporations, other LLCs and foreign entities.
For federal tax purposes, an LLC must file as a corporation, partnership, or sole proprietorship tax return.
Follow the form requirements for partnerships or corporations as stated above for LLCs.

=== Boarder Income

A recipient with boarder income is entitled to a cost of doing business deduction, which is equal to the maximum SNAP allotment for an AU size equal to the number of boarders or 40% of the gross self-employment income to cover the cost of doing business, if greater than the maximum SNAP allotment.
The amount of an expense allowed as a cost of doing business cannot exceed the payment the recipient receives from the boarder for lodging and meals.

=== Rental Property

To determine self-employment income from rental property, the number of hours spent doing business must be considered.
Refer to xref:3420.adoc#chart-3420-2[Chart 3420.2, Types of Income].

|===
^| IF AU MEMBER(S) ARE ^| THEN COUNT

| actively involved in property management at least 20 hours per week,
| the gross income less the cost of doing business as earned income.

| not actively involved in property management at least 20 hours per week,
| the gross income less the cost of doing business as unearned income.
|===

=== Farm Losses

If the cost of producing self-employment farm income exceeds the gross farm income, the losses are offset against other countable income.
To qualify for this offset, the AU must receive or anticipate receiving annual gross proceeds of $1,000 or more from the farming enterprise.

Monthly net farm self-employment income is computed in the normal manner by taking gross income, subtracting allowable expenses and prorating the result over the period the income is intended to cover.

If there is a monthly net farm loss, offset the loss as follows:

* Offset the loss against the net amount of any other self-employment income for the month(s).
* If the other net self-employment income is not enough to cover the farm loss, the remainder of the farm loss is offset against the other countable gross amount of earned and unearned income for that month.

NOTE: Allow the 20% earned income deduction before deducting the loss offset.

If there is still a net loss, the AU is certified based on zero net.

The monthly loss is not carried forward to subsequent months.
Consider each month's income and expenses separately.

=== Treatment of Income

Annualize self-employment income if the following occurs:

* the self-employment income represents a year's support, even if the income is received in a short time period
* the self-employment income accurately reflects the AU's current circumstances

NOTE: Annualize the self-employment income even if the AU receives additional income from other sources.

Do not annualize self-employment income if the following occurs:

* the self-employment income is not an accurate picture of the AU's current circumstances because income has recently increased or deceased
* the self-employment income represents support for only a part of the year
* the self-employment income is from a new business in operation less than one year.

To determine monthly income for an annualized self-employment situation, total gross receipts of annual income, allow the 40% deduction for the cost involved with the self-employment endeavor, and divide by twelve.

Use the policy in <<chart-3425-1,Chart 3425.1>> below to determine allowable business expenses.

[#chart-3425-1]
.CHART 3425.1 COSTS OF DOING BUSINESS
|===
^| ALLOWABLE EXPENSES  (Not All-Inclusive) ^| UNALLOWABLE EXPENSES  (All-Inclusive)

a| Costs associated with self-employment enterprise, such as:

labor costs

costs of stock, raw material, seeds, fertilizer

payments (principal and interest) for the purchase price of income-producing real estate and capital assets, equipment, machinery, and other durable goods

insurance premiums on income-producing property such as real estate or equipment

taxes paid on income-producing property

privilege taxes paid for such items as licensing fees, gross receipts and general excise taxes that must be paid in order to earn self-employment income

rental payment on income-producing equipment

costs, repairs, and maintenance of income-producing equipment or stock

job-related transportation costs

costs of home business-

* prorate the household expenses (mortgage/rent, utilities) by the number of rooms used for the business.
a| net losses from previous periods.

federal, state, and local income taxes.

income set aside for retirement.

work-related personal expenses (transportation to and from work, living expenses).

depreciation on equipment, real estate, etc.
Depreciation occurs when a resource loses value because of any destruction of property in a storm, fire or other reason, and long-term use of resources reduces value, (e.g. vehicles).

any amount that exceeds the payment an AU receives from a boarder for lodging and meals.

NOTE: These expenses may be used to determine taxable income for IRS and tax purposes, but may not be used for the determination of income for SNAP purposes.
|===

NOTE: If using household expenses as self-employment expenses, allow the remainder not used as a self-employment expense as the shelter expense.

If using the SUA for shelter deduction, do not prorate.
Allow the SUA as a shelter expense and not a self-employment expense.
If using the SUA for shelter, only a business phone expense can be allowed as a self-employment expense.

Use the policy in <<chart-3425-2,Chart 3425.2>> below to determine the treatment of income not annualized.

[#chart-3425-2]
.CHART 3425.2 HOW TO COMPUTE INCOME WHICH IS NOT ANNUALIZED
|===
^| IF THE INCOME ^| THEN

| does not reflect current circumstances (recent increase or decrease in income)
| determine the best estimate of current gross monthly income, minus 40%, and use as the monthly amount budgeted.

| is from a new business, i.e., in operation less than one year
| average gross income, subtract 40%, divide by the period of operation to determine the monthly budgeted income.

| represents only part of the year's income
| average gross income, subtract 40%, divided by the number of months the income is intended to cover, and budget that amount as monthly income.

| is received monthly
| budget total gross monthly income, minus 40%.
|===

== Procedures

Follow the steps below to determine the income that should be counted in the budget:

Add all gross self-employment income.

Add any capital gains.

Subtract 40%.

Divide the remaining amount by the number of months over which the income is intended to cover.
The result is the monthly net self-employment income.
Add the monthly net self-employment income to the other countable earned income.

Add unearned income to adjusted gross earned income.

Calculate deductions and benefit level as for any other AU.

Refer to xref:3610.adoc[].

== Verification

Verify through the use of SteadyIQ (if available), tax files, business records, receipts, bills, or a written statement from the client attesting to the established business and self-employment earnings.

For a new business, verify through the use of available information provided by the AU to determine a best estimate.
