= 3614 Excess Medical Deduction
:chapter-number: 3600
:effective-date: June 2026
:mt: MT-87
:policy-number: 3614
:policy-title: Excess Medical Deduction
:previous-mt-number: MT-83

include::partial$policy-header.adoc[]

== Codes and References

7 CFR § 273.9(d)(3)

== Requirements

The excess medical deduction is given to an assistance unit (AU) that has at least one eligible member who is elderly (60 years of age or older) or disabled as defined by Supplemental Nutrition Assistance Program (SNAP)  policy.

== Basic Considerations

=== Excess Medical Deduction

Medical expenses in excess of $35 per month that are incurred by an AU member who is elderly or disabled (as defined in the glossary) are considered when determining the excess medical deduction.
The $35 applies to the *total* monthly expenses incurred by all elderly or disabled household members; it does not apply to each person’s expenses if more than one person in the household is elderly or disabled.

Determine the expenses that are for the AU member who is eligible to receive the deduction.
The medical expenses of an individual, who was an AU member immediately before being hospitalized, institutionalized, or dying would be allowed if the AU remains legally responsible for payment of the medical expenses.

If the following conditions are met, allow the medical expense(s):

* The AU member can provide current verification of the medical expense.

* The AU member incurs the expense, even if actual payments have not been made.
Medical expenses are allowed as billed, not as paid.

* There is no reimbursement from a third party (health insurance, Medicare, Medicaid, etc.).
Any reimbursement amount must be verified.
+
NOTE: If an application for Medicaid, financial assistance, or other health insurance coverage is pending, do not allow any medical expenses until the AU's liability for payment of the bill is identified.

* The medical bill has not been allowed as a deduction in a previous SNAP budget (approval or denial).
Once a bill is allowed as a deduction, it *cannot* be allowed again.

If the medical expenses are billed through a credit card (e.g., Master card, VISA, etc.), only the expense is considered as the deduction, not the interest.
Count the expenses as billed in the month that includes the medical expense(s), and not the month the bill was due, if those months differ.

Verify the current status of bills turned over to a collection agency and allow the expenses if the AU incurs or is billed for the expenses, provided the expenses have not been previously allowed in a SNAP budget.

Households may receive a medical expense deduction for payments made on a conventional loan when the loan is used to pay a one-time only medical expense, but loan expenses (such as interest) are not allowable as part of the deduction.

NOTE: If a household obtains a mortgage for the purpose of financing a large medical expense, the mortgage payments should be treated as shelter costs and are not deductible as medical expenses.


Do not shorten an AU's certification period to allow an excess medical deduction.

=== Community Care Services Costs

The monthly cost share paid by an individual for services received through the Community Care Services Program (CCSP) may be considered an incurred medical expense.
The cost share is the maximum amount an individual is required to pay for services in any given month.
If the total cost of services received does not equal the established cost share, the individual is responsible only for the actual cost of services.
The cost share paid must be for an [.underline]#allowable# medical expense to be considered a SNAP medical deduction.

=== Medically Needy Spend Down

The medically needy spend-down amount is not a medical expense by itself.
The bills used in a medically needy budget may be used as medical expenses if they are allowable medical expenses in SNAP.

=== Medical Expenses

Medical expenses are categorized into two types.
They are:

* [.underline]#one-time only expenses# such as charges for a hospital stay.
The non-reimbursable amount of the one-time only expense may be allowed as a deduction in one month only or averaged over the certification period.

* [.underline]#recurring expenses# such as the monthly costs for prescription drugs, Medicare premiums, insurance premiums, doctor visits, and transportation costs (mileage driven to and from the doctor or pharmacy).
Recurring medical expenses are allowed as a deduction by either varying the basis of issuance (actual expenses each month) or averaging ongoing expenses.

NOTE: Special Diets are not an allowable medical expense deduction even if they are prescribed or approved by a licensed practitioner recognized by the State. “Special Diets” include those prescribed for people with diabetes, prescribed liquid diets and nutritional supplements (Ensure, Nutritional Products, Complete Regular Formula, Enrich, Jevity, Osmolite), allergy-free foods, special diets necessitated by religious considerations, and any item (including organic or fresh food and bottled water) that can be otherwise purchased with SNAP benefits.
Schedule I controlled substances are not allowable medical expenses under Federal law, regardless of whether they have been prescribed in accordance with State law. Under the Controlled Substances Act, marijuana is a Schedule I controlled substance and is not allowed as a medical expense.


=== Verification

Verify *current*, non-reimbursable expenses for all AU members who are 60 years of age or older or who are disabled.
If the total expenses do not exceed $35 monthly, then verification is not required.

Reimbursement of a medical expense is verified before allowing the expense. Verify the amount of reimbursement from a third-party source and subtract it from the total medical expense before allowing the expense as a deduction.

Verify medical expenses:

* at initial application
* recertification (renewal), Refer to xref:3710.adoc[Section 3710], Recertifications (Renewals)
* interim change, Refer to xref:3715.adoc[Section 3715], Interim Changes (OR)
* when information is questionable.

Suggested forms of verification are:

* paid receipts;
* written statements from attendants or providers;
* health insurance policies or payment books that indicate the type of policy (health) and amount of premium;
* current bills for physician and pharmacy services;
* pharmacy printout for prescriptions;
* Form xref:attachment$form-840.pdf[840], Medical Transportation Log;



=== Documentation

Document the case notes with the following information:

* allowable deductions
* the amount of reimbursements and the source
* source of verification of medical expenses
* calculation of medical deduction
* reason medical expense was not allowed as a deduction.

=== Medicare Part - D

Medicare Part D is a prescription drug insurance plan designed to assist Medicare and Medicaid recipients with the high costs of prescription drugs.
Enrollment in Medicare Part D began on 11/15/2005.
The Medicare Discount Card Plans are valid until enrollment in Medicare Part D or 5/15/06, whichever is earlier.
The medical expenses of Medicare and Medicaid recipients enrolled in Medicare Part D prescription drug plans are budgeted using the regular SNAP policy guidelines.
For example, co-payments, plan premiums, and deductibles, if any, are allowable expenses for the medical deduction.

All SSI recipients and other low-income recipients receiving ABD classes of assistance will be automatically enrolled in a Medicare Part D plan.

*Those who are considered low-income should pay no premium.*

=== Standard Medical Deduction

Georgia is approved to allow households to claim a standard medical deduction (SMD) if there is an elderly or disabled household member with recurring medical expenses of more than $35 per month.
*Effective October 1, 2023,* the approved SMD is $161 ($196 - $35 = $161) per month.
Only one standard medical deduction can be given per AU.

There are two types of medical deductions that may be applied to elderly/disabled individuals: 1) Standard Medical Deduction *OR* 2) a deduction for Actual Medical Expenses incurred.

* To be eligible for the *Standard Medical Deduction*, households must verify that they incur more than $35 per month in qualifying medical expenses.
The household may verify medical expenses using [.underline]#*one*# medical bill that is more than $35 per month to qualify for the standard medical deduction.
+
NOTE: The household does *NOT* have to verify all medical expenses to qualify for the standard medical deduction if one bill is more than $35.

* Households with recurring medical expenses that are more than $196 per month may opt to claim *Actual Medical Expenses* and verify all medical expenses.
To be eligible for a deduction using actual expenses, the household must verify *all* medical expenses to receive a deduction that is more than the standard medical deduction.

SNAP households will remain eligible for the standard medical deduction at recertification (renewal) if they state that their medical expenses continue to exceed $35 per month.
Verification of medical expenses is not required at recertification (renewal) unless the client's statement is questionable.

*_Initial Application_* - To allow the deduction, qualifying expenses of more than $35 per month must be verified.
If requested verification is not provided, the expense will not be allowed.
Households may report expenses of more than the standard medical deduction, making actual medical expenses the better option.
When a client opts for actual expenses, all medical expenses must be verified.

*_Recertification (Renewal)_* - Households will remain eligible for the standard medical deduction at recertification as long as the AU reports they still have allowable medical expenses of more than $35 per month.
Verification will not be required unless the client's statement is questionable.
If the standard medical deduction was previously allowed but the AU failed to report medical expenses on the recertification form (i.e. did not respond to the medical expense section or checked NO expenses), a telephone contact to determine whether medical expenses should continue is required.
If the client cannot be reached by telephone, the case manager will leave a message (when possible) and document the agency's attempt to follow up.
The case manager will send the Verification Checklist (VCL), allowing 10 days for the household to respond.
If there is no response, the standard medical deduction will be removed, and the case will be completed without the deduction.
When the client opts for actual expenses, all medical expenses must be verified.

*_Interim Change_* – There are no new reporting requirements for medical expenses.
Verification will be required when the household reports new medical expenses that would qualify the AU for the standard or for actual medical expenses.
If requested verification is not provided, the expense will not be allowed as a deduction.

=== Documentation Requirements

In Gateway, document in client-level notes the qualifying expense(s) used when allowing the household, the Standard Medical Deduction.
Document the reason why reported medical expenses were not given for potentially eligible AU members, such as current expenses, or non-reimbursed expenses not verified.

The following examples are to be used as a guide when applying the Standard Medical Deduction or a deduction for actual medical expenses to SNAP cases:

*Example 1*: A/R reports $998 per month RSDI + $104.90 recurring pharmacy prescription for an elderly AU member.
RSDI is verified by BENDEX.
Recurring pharmacy prescription is verified by pharmacy printout and is more than $35 per month but less than $196.
*The client is eligible for the standard medical deduction*.

*Example 2*: At initial application, the client reports he is disabled and has a one-time hospital bill that is more than $35 per month.
The client provides a $250 hospital bill.
Using the 12-month certification period to determine the monthly amount, $250/12 = $20.83.
The verified monthly medical expense [.underline]#*is less*# than $35 a month.
[.underline]#*Please note*#: To determine if a *one-time* bill qualifies a customer for the Standard Medical Deduction, the total bill must be averaged over the certification period to determine the monthly amount.
This must be documented in the client case notes.
*_The client is not eligible for the standard medical deduction but may receive a one-time deduction for the hospital bill._*

*Example 3*: At recertification, a client recently approved for Social Security disability provides a $100 one-time doctor bill.
Using the 12-month certification period to determine the monthly amount, $100/12=8.33/month for this bill.
The client also reports recurring prescription costs of $20 per month and recurring transportation costs of $10 per month.
The total verified medical expenses = $38.33 (8.33+20+10 = $38.33).
The medical expenses exceed $35 per month but are less than $196 per month.
*_The client is eligible for the standard medical deduction using combined prorated and recurring expenses_*.

*Example 4*: An elderly client owns a vehicle and reports he drives 65 miles each month to medical appointments and the pharmacy.
65 miles per month x .725 (current state mileage rate) = $47.13 per month for transportation costs.
The medical expenses exceed $35 per month but are less than $196 per month.
When mileage is reported as a transportation medical expense, the client’s statement is accepted if the customer uses a vehicle owned by someone in the AU.
*_The client is eligible for the standard medical deduction._*

*Example 5:* A disabled client pays a recurring Medicare premium in the amount of $204.90 per month which is verified via BENDEX.
The client indicated during the interview that they have recurring prescriptions that total $55 per month.
The total medical expenses = $259.90 (204.90+55 = $259.90).

*_Because the client's medical expenses exceed $196 per month and are more than the standard deduction amount, the client may opt to claim and verify all medical expenses and receive a deduction for actual medical expenses incurred.
Claiming actual expenses would be more advantageous to the client vs. allowing the standard medical deduction._*

[.underline]#Client deduction claimed with standard medical deduction# - $196-$35 = *$161 per month.*

[.underline]#Client deduction claimed with actual medical expenses# - $259.90-$35 = *$224.90 per month*.

The household should receive *$224.90 per month* as a medical deduction since it is more than what would be received under the standard medical deduction.

Use the following chart to identify allowable medical expenses used in determining financial eligibility:

[#chart-3614-1]
.CHART 3614.1 - ALLOWABLE MEDICAL COSTS
|===
^| EXPENSE ^| EXPLANATION

| Medical and dental services
| Includes psychotherapy, chiropractors, and rehabilitation services.

| Hospitalization, outpatient treatment, or nursing care
| Includes payments by the AU for an individual who was an AU member immediately before entering a hospital, nursing home or before death.

| Prescription drugs, over-the-counter medications, and medical supplies
| Must be prescribed by a licensed practitioner.

| Sick room or emergency response equipment
| May be rented or purchased.

| Eyeglasses, contact lenses, dentures, hearing aids, prosthesis
| Prescribed by a licensed practitioner.

| A medical expense paid by a resident of a group living arrangement
| Must be separate from food and shelter payments and paid from the resident's own income.

| Service animals to assist a disabled AU member
| Include the cost of securing and maintaining the animal, i.e., food and veterinary bills.
Service animals must be specially trained to assist the SNAP recipient in order for its associated maintenance costs to be an allowable deduction.
If the animal has not been specially trained, it is not a service animal, and its expenses are not allowed as a deduction.

| Transportation (including doctor and pharmacy visits) and lodging to secure medical treatment or medical services
| Mileage driven to and from the doctor's office and pharmacy to pick up prescriptions may be allowed as a medical deduction if at least one of the household's vehicles is used for transportation.
The vehicle must belong to a member of the SNAP AU.
The mileage rate as established for State employees, plus parking (when the individual uses a household vehicle), is used to calculate medical transportation costs.

Obtain the current mileage rate for state employees.
Use actual costs for all other types of transportation (i.e., bus, train, taxi, Uber, Lyft, etc.).

*NOTE:* Client's statement can be accepted for mileage related to medical transportation.

| Maintenance of an attendant, homemaker, home health aide, childcare services, or housekeeper necessary because of age, infirmity, or illness
| Allow the cost of the expense as a medical deduction.
In addition, if the AU furnishes the majority of an attendant's meals, deduct an amount equal to the maximum one-person allotment in effect at approval.
Update the allotment amount at each recertification.

| Health, hospitalization, long-term care/nursing home insurance premiums, Medicare supplement premiums, prescription drug insurance
| Allow only the portion of the insurance premium that applies to the AU member eligible for the deduction.
If specific information on how much of the premium applies to the eligible AU member is not available, prorate the total amount.

For long-term care/nursing home insurance premiums, allow only costs that cover medical, nursing home care and live-in attendant care.
Costs that cover normal living expenses are not allowed as a deduction.

| Medicare premiums
a| A Medicare premium that is paid by the AU member is allowed.

[caption=Exception]
NOTE: When the A/R is approved for or receiving Medicaid, which will pay the Medicare premium, the premium must not be allowed as a deduction in the SNAP budget.

| Payments by residents of drug/alcohol treatment centers
| Payments must be for separate and identifiable medical costs at the center.

| The cost of telephone equipment specially equipped for a disabled person
| Includes monthly telephonic fees for amplifiers and warning signals, and the cost of typewriter equipment plugged into the telephone system for use by deaf people.

A physician's statement is required to verify medical need.
|===

Use the following chart to determine how to budget one-time-only medical expenses.

[#chart-3614-2]
.CHART 3614.2 - BUDGETING ONE-TIME-ONLY MEDICAL EXPENSES
|===
^| IF THE MEDICAL EXPENSE IS ^| THEN

| incurred prior to initial application,
a| allow the current non-reimbursable balance as a medical expense.

NOTE: The deduction can be applied in a month during the application period in which the AU will receive a full month of benefits.

| incurred, reported, and verified in the application month (could be paid or have an existing balance),
| allow the full non-reimbursable amount as a medical expense.

| incurred, reported, and verified within the current certification period,
| allow the full non-reimbursable amount as a medical expense.

| incurred during the current certification period and reported and/or verified in the last month of the current certification period

*AND*

the AU reapplies (in the last month of the current certification period or in the following month),
| allow the full non-reimbursable amount as a medical expense in the new certification period.

| incurred in a prior certification period but reported and/or verified in the current certification period,
| allow the *current* non-reimbursable balance as a medical expense. Past due amounts cannot be included.

| paid on an installment plan (does not include charge card or loans),
| allow the actual installment amount each month, even if payments extend beyond the end of the certification period.
|===

NOTE: One-time-only medical expenses are allowed as a one-time-only expense or averaged over the remainder of the certification period.
The AU has an option to choose.

Use the following chart to determine how to budget recurring expenses.

[#chart-3614-3]
.CHART 3614.3 - BUDGETING RECURRING MEDICAL EXPENSES
|===
^| IF ^| THEN

| AU member chooses to average ongoing expenses,
| Determine the monthly non-reimbursable amount of each medical expense.

Divide by the number of months the expenses are intended to cover to arrive at a monthly amount that best represents the amount the AU normally pays.
Include any intervening months.
For example, AU pays $100.00 every other month for a non-reimbursable prescription.
The prescription is intended to cover a 2-month period.
Divide $100.00 by two to obtain a monthly figure of $50.00.

Total the monthly amounts of all non-reimbursable recurring medical expenses.
Use a history of recurring expenses to determine monthly expenses.
Look at the frequency of incurred expenses.

Allow the monthly expenses as a deduction for the period of time the AU anticipates the expense will continue.

| AU chooses variable basis issuance,
| Determine the monthly non-reimbursable cost of each medical expense.

The AU must verify the amount of the reimbursable monthly costs each month.
The expense is not allowed in any month for which verification is not provided.
The benefit amount is adjusted according to the deduction that is determined.

Total the monthly amount of all non-reimbursable recurring medical expenses.
|===

Recurring expenses are allowed as a deduction by either averaging or using variable issuance (actual costs).
The AU has an option to choose.
