= 3705 Notification
:chapter-number: 3700
:effective-date: November 2025
:mt: MT-85
:policy-number: 3705
:policy-title: Notification
:previous-mt-number: MT-75

include::partial$policy-header.adoc[]

== Codes and References

7 CFR § 273.13

== Requirements

Written notice to the AU is required when any of the following occurs:

* Approval or denial of an application for benefits;
* Eligibility determination at recertification;
* Eligibility determination at periodic report;
* An increase or decrease in the benefit level;
* Addition or deletion of an individual in an AU;
* Denial or termination of an individual's benefits because of a sanction, IPV disqualification, or ineligibility;
* Shortening of the certification period;
* Termination of all benefits to the AU.

== Basic Considerations

Written notifications must include the following:

* The proposed action;
* The reason for the action;
* The effective month of the action;
* The AU's right to a fair hearing;
* The conditions for continued benefits;
* The AU's liability for benefits received during the hearing process;
* The availability of free legal representation;
* The telephone number and name of a person to contact for additional information;
* For denials, the action the AU must take to reopen the application (if action is taken within 60 days of the date of application), *AND*
* That the AU must submit a new application if, at the end of the 60-day period, the AU has not taken the required action to reopen the application.

Written notice is program-specific and is generated by the system.
When the system-generated notice's explanation is inadequate, additional documentation on the notice is required.
Form 333, Disposition Notification SNAP Sanction/Penalty, is used to notify an AU of changes due to sanctions.

Written notice can be mailed to the AU or hand-delivered to the AU during an interview.

== Procedures

=== Adequate Notice

*Adequate notice* is written communication provided to the AU no later than the date the action is taken.

Provide adequate notice in the following circumstances:

* Mass changes in benefits initiated by the State or Federal government, including the following:
** TANF, RSDI, and SSI adjustments
** Financial standards and benefit levels
** SNAP budget deductions

* Death of all members of the AU reported through reliable information;

* At initial application
* At recertification
* Household fails to complete the required periodic report and provide all required verification;

* Household voluntarily requests in writing or in the presence of a case worker (face to face or phone), voluntary termination of benefits for the entire AU;

* Disqualification for Intentional Program Violation (IPV);

* The entire AU moves out of state;

* Lost benefits have been completely restored;

* Benefit reduction upon approval of TANF, and the AU was previously notified of the possible reduction;

* Benefit adjustment upon receipt of postponed verification for AUs that received expedited processing;

* When a strike is settled;

* A drug or alcohol treatment center or group living arrangement acting as an authorized representative loses its certification, which results in the AU's ineligibility;

* The AU reports information in writing, signed by a responsible AU member, and the benefit reduction or ineligibility can be determined without verification;

* Benefits were approved for a specific time period, and the AU was informed in writing of the proposed reduction, termination, or change in benefits at approval.

* Sanctions on closed cases or in the final month of the certification period;

* Sanctions imposed at application.

=== Timely Notice

*Timely notice* is written communication provided to the AU in which a 14-day waiting period is given before the date the proposed action becomes effective.

Provide timely notice in circumstances where it is mandated by policy.

Implement the proposed change effective the month following expiration of the 14- day timely notice period.

If the AU provides information within the 14-day timely notice period that alters the proposed change, stop the action and re-evaluate the AU's circumstances to determine eligibility.

Allow the system to automatically track the 14-day timely notice period if the action is entered in the system.

Manually track the 14-day timely notice period if a manual notice is sent.

The AU may request a fair hearing and continuation of benefits within the timely notice period.
Refer to Appendix B, Hearings.
